server:
  port: 8080

spring:
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

playlist:
  jwt:
    access-token:
      secret: ${JWT_ACCESS_TOKEN_SECRET}
      expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS:3600000} # 1시간
    refresh-token:
      secret: ${JWT_REFRESH_TOKEN_SECRET}
      expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS:604800000} # 7일
    cookie:
      secure: true
  s3:
    content-bucket: playlist-content-bucket
    profile-bucket: playlist-profile-bucket
    logs-bucket: playlist-logs-bucket
    backup-bucket: playlist-backup-bucket

logging:
  level:
    root: info
    com.codeit.playlist: info
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
    org.springframework.security: info

management:
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
